-- Seeding wf_brand
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (1, '3M', 'C-MOVIL', 28, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (2, 'AFA', 'C-MOVIL', 90, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (3, 'ASAHI', 'C-MOVIL', 180, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (4, 'AUTOTRAVI', 'C-MOVIL', 120, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (5, 'BEN', 'C-MOVIL', 240, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (6, 'CAÑERIA DE COBRE', 'C-MOVIL', 110, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (7, 'CAÑERIA DE FRENO', 'C-MOVIL', 115, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (8, 'CAUPLAS', 'NOVAPARTES', 120, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (9, 'CHAMPION', 'PROLINE', 210, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (10, 'CONTROIL', 'NOVAPARTES', 90, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (11, 'CORCHO ENGOMADO', 'C-MOVIL', 120, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (12, 'CTR', 'NOVAPARTES', 195, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (13, 'FANADEGO', 'C-MOVIL', 120, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (14, 'FIC', 'C-MOVIL', 182, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (15, 'FLEXRITE', 'C-MOVIL', 120, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (16, 'FRASLE', 'NOVAPARTES', 120, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (17, 'FRITEC', 'C-MOVIL', 158, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (18, 'GATES', 'C-MOVIL', 120, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (19, 'GAUSS', 'C-MOVIL', 150, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (20, 'GMB', 'C-MOVIL', 230, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (21, 'GSP', 'C-MOVIL', 155, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (22, 'HI LITE', 'C-MOVIL', 180, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (23, 'HI POWER', 'C-MOVIL', 180, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (24, 'HO', 'C-MOVIL', 150, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (25, 'HP FILTROS', 'C-MOVIL', 190, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (26, 'HP FRENO', 'NOVAPARTES', 210, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (27, 'HP LIMPIAPARABRISAS', 'C-MOVIL', 210, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (28, 'HWC', 'C-MOVIL', 180, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (29, 'IMPERIAL', 'C-MOVIL', 30, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (30, 'KIKI', 'C-MOVIL', 30, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (31, 'KRUG', 'C-MOVIL', 170, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (32, 'LUCIFLEX', 'C-MOVIL', 90, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (33, 'MARILIA', 'C-MOVIL', 90, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (34, 'MGI', 'C-MOVIL', 210, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (35, 'MITSUBOSHI', 'C-MOVIL', 252, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (36, 'MIYACO', 'C-MOVIL', 300, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (37, 'MRK', 'C-MOVIL', 210, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (38, 'MULTILIGHT', 'C-MOVIL', 90, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (39, 'MUSASHI', 'C-MOVIL', 240, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (40, 'NGK', 'C-MOVIL', 150, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (41, 'NIKKO', 'C-MOVIL', 295, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (42, 'NOK', 'C-MOVIL', 30, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (43, 'NPR', 'C-MOVIL', 266, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (44, 'NPW', 'NOVAPARTES', 240, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (45, 'PEVISA', 'C-MOVIL', 150, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (46, 'PHC VALEO', 'C-MOVIL', 150, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (47, 'REI', 'C-MOVIL', 30, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (48, 'RHC', 'C-MOVIL', 30, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (49, 'SANKEI DREIK', 'C-MOVIL', 240, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (50, 'SEIWA', 'C-MOVIL', 30, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (51, 'SIL', 'C-MOVIL', 90, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (52, 'SORL', 'C-MOVIL', 181, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (53, 'SUPRENS', 'C-MOVIL', 90, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (54, 'TAIDO', 'NOVAPARTES', 180, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (55, 'TAIDO SOLENOIDES', 'NOVAPARTES', 240, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (56, 'TAMA', 'C-MOVIL', 30, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (57, 'TOYO', 'NOVAPARTES', 210, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (58, 'TRAMONTINA ELETRIK', 'N/A', 0, FALSE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (59, 'TRAMONTINA HAGALO', 'C-MOVIL', 30, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (60, 'TRAMONTINA MASTER', 'C-MOVIL', 60, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (61, 'TRAMONTINA MULTI', 'N/A', 0, FALSE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (62, 'TRAMONTINA PRO', 'C-MOVIL', 30, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (63, 'VALEO', 'NOVAPARTES', 120, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (64, 'VIEMAR', 'NOVAPARTES', 90, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (65, 'WAGNER FRENOS', 'PROLINE', 90, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (66, 'WAGNER LIQUIDOS', 'PROLINE', 95, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (67, 'WEGA', 'C-MOVIL', 65, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (68, 'ZM', 'C-MOVIL', 168, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;
INSERT INTO wf_brand (id, name, u_negocio, leadtime, active) VALUES (69, 'ZUTAKA', 'C-MOVIL', 240, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, u_negocio = EXCLUDED.u_negocio, leadtime = EXCLUDED.leadtime, active = EXCLUDED.active;

-- Resetting wf_brand sequence
SELECT setval(pg_get_serial_sequence('wf_brand', 'id'), COALESCE(MAX(id), 1)) FROM wf_brand;

-- Retro-classifying existing instances
UPDATE wf_instance SET brand_id = 37 WHERE id = 3;
UPDATE wf_instance SET brand_id = 35 WHERE id = 6;
UPDATE wf_instance SET brand_id = 35 WHERE id = 7;
UPDATE wf_instance SET brand_id = 67 WHERE id = 8;
UPDATE wf_instance SET brand_id = 35 WHERE id = 16;
UPDATE wf_instance SET brand_id = 33 WHERE id = 17;
UPDATE wf_instance SET brand_id = 33 WHERE id = 18;
UPDATE wf_instance SET brand_id = 35 WHERE id = 19;
UPDATE wf_instance SET brand_id = 35 WHERE id = 20;
UPDATE wf_instance SET brand_id = 40 WHERE id = 21;
UPDATE wf_instance SET brand_id = 40 WHERE id = 22;
UPDATE wf_instance SET brand_id = 40 WHERE id = 23;
UPDATE wf_instance SET brand_id = 33 WHERE id = 24;
UPDATE wf_instance SET brand_id = 40 WHERE id = 25;
UPDATE wf_instance SET brand_id = 33 WHERE id = 26;
UPDATE wf_instance SET brand_id = 33 WHERE id = 27;
UPDATE wf_instance SET brand_id = 35 WHERE id = 28;
UPDATE wf_instance SET brand_id = 35 WHERE id = 29;
UPDATE wf_instance SET brand_id = 35 WHERE id = 30;
UPDATE wf_instance SET brand_id = 35 WHERE id = 31;
UPDATE wf_instance SET brand_id = 35 WHERE id = 32;
UPDATE wf_instance SET brand_id = 35 WHERE id = 33;
UPDATE wf_instance SET brand_id = 35 WHERE id = 34;
UPDATE wf_instance SET brand_id = 35 WHERE id = 35;
UPDATE wf_instance SET brand_id = 35 WHERE id = 36;
UPDATE wf_instance SET brand_id = 35 WHERE id = 37;
UPDATE wf_instance SET brand_id = 35 WHERE id = 38;
UPDATE wf_instance SET brand_id = 35 WHERE id = 39;
UPDATE wf_instance SET brand_id = 33 WHERE id = 40;
UPDATE wf_instance SET brand_id = 33 WHERE id = 41;
UPDATE wf_instance SET brand_id = 33 WHERE id = 42;
UPDATE wf_instance SET brand_id = 33 WHERE id = 43;