# Ignorar la carpeta de configuración local de Streamlit
.streamlit/secrets.toml
.streamlit/

# Ignorar el entorno virtual de Python (si lo creaste en tu carpeta)
venv/
.venv/
__pycache__/

[email]
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "edwincolquev@gmail.com"
SENDER_PASSWORD = "pegu pkqq bpvn tcne"


base datos: workflow-m7
clave: 4jLJCupK9Af1N5UX