# DATABASE_URL = "postgresql://postgres.[tu-proyecto]:[tu-password]@[region].pooler.supabase.com:6543/postgres"
DATABASE_URL="postgresql://postgres.vistjnuohkunrrgifolw:Ix0nCXnTZn4ysdvQ@aws-1-us-east-2.pooler.supabase.com:6543/postgres?pgbouncer=true"


# Configuración de correo SMTP
[email]
#base_url = "https://workflow-m7.streamlit.app"

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "edwincolquev@gmail.com"
SENDER_PASSWORD = "pegu pkqq bpvn tcne"


# Notas de referencia (no usar como claves)
# base datos: workflow-m7
# clave: 4jLJCupK9Af1N5UX


#[sap_db]
#driver = "{ODBC Driver 17 for SQL Server}"
#server = "IP_O_HOST_DEL_SERVIDOR"
#database = "NOMBRE_DB_SAP"
#username = "USUARIO_DB"
#password = "PASSWORD_DB"
#timeout = 5